# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 23:59
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='cropping',
            field=image_cropping.fields.ImageRatioField(b'image', '262x377', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
