# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyvalue',
            name='value',
            field=models.IntegerField(),
        ),
    ]
