# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_productimage_cropping'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attached',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='isPopular',
            field=models.BooleanField(default=False),
        ),
    ]
