# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 22:11
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170330_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.ImageField(default='', upload_to=b'page'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='page',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
