# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_news_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_slider',
            field=models.BooleanField(default=False, verbose_name='\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c \u0432 \u0441\u043b\u0430\u0439\u0434\u0435\u0440'),
        ),
    ]
