# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_news_is_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytype',
            name='unit',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True),
        ),
    ]
