# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170405_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to=b'certificate'),
        ),
    ]
