# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170508_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hotImage',
            field=models.ImageField(blank=True, null=True, upload_to=b'product'),
        ),
        migrations.AddField(
            model_name='product',
            name='isHotSlider',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='cropping',
            field=image_cropping.fields.ImageRatioField(b'image', '300x222', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
