# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 12:35
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170508_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='croppingVertical',
            field=image_cropping.fields.ImageRatioField(b'image', '250x375', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='croppingVertical'),
        ),
    ]
