# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_productimage_croppingvertical'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='mainCropper',
            field=models.CharField(choices=[(b'horizontal', b'horizontal'), (b'vertical', b'vertical')], default=b'horizontal', max_length=240, verbose_name='\u041e\u0441\u043d\u043e\u0432\u043d\u043e\u0439 \u043e\u0431\u0440\u0435\u0437\u0447\u0438\u043a'),
        ),
    ]
