# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 13:13
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_productimage_maincropper'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='thumb',
            field=image_cropping.fields.ImageRatioField(b'image', '60x60', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='thumb'),
        ),
    ]
