# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0004_auto_20160305_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitephone',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configs.Config'),
        ),
        migrations.AlterField(
            model_name='sitephone',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='\u0413\u043b\u0430\u0432\u043d\u044b\u0439 \u0442\u0435\u043b\u0435\u0444\u043e\u043d'),
        ),
    ]
