# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0005_auto_20160305_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='site_email',
            field=models.CharField(default='', max_length=200, verbose_name='\u041f\u043e\u0447\u0442\u0430 \u0430\u0434\u043c\u0438\u043d\u0438\u0441\u0442\u0440\u0430\u0442\u043e\u0440\u0430'),
            preserve_default=False,
        ),
    ]
