# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0006_config_site_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='site_address',
            field=models.CharField(default='', max_length=200, verbose_name='\u0410\u0434\u0440\u0435\u0441 \u0441\u0430\u0439\u0442\u0430'),
            preserve_default=False,
        ),
    ]
