# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0007_config_site_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='site_logo2',
            field=models.ImageField(default='', upload_to=b'config'),
            preserve_default=False,
        ),
    ]
