# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('cart_id', models.CharField(max_length=240)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.PropertyValue')),
            ],
            options={
                'verbose_name': '\u041e\u0431\u044a\u0435\u043a\u0442 \u043a\u043e\u0440\u0437\u0438\u043d\u044b',
                'verbose_name_plural': '\u041a\u043e\u0440\u0437\u0438\u043d\u0430',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, max_length=240, null=True)),
                ('area_type', models.CharField(blank=True, max_length=240, null=True)),
                ('block', models.CharField(blank=True, max_length=240, null=True)),
                ('block_type', models.CharField(blank=True, max_length=240, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=240, null=True)),
                ('country', models.CharField(blank=True, max_length=240, null=True)),
                ('region', models.CharField(blank=True, max_length=240, null=True)),
                ('region_type', models.CharField(blank=True, max_length=240, null=True)),
                ('city', models.CharField(blank=True, max_length=240, null=True)),
                ('city_type', models.CharField(blank=True, max_length=240, null=True)),
                ('street', models.CharField(blank=True, max_length=240, null=True)),
                ('street_type', models.CharField(blank=True, max_length=240, null=True)),
                ('settlement', models.CharField(blank=True, max_length=240, null=True)),
                ('settlement_type', models.CharField(blank=True, max_length=240, null=True)),
                ('house', models.CharField(blank=True, max_length=240, null=True)),
                ('house_type', models.CharField(blank=True, max_length=240, null=True)),
                ('flat', models.CharField(blank=True, max_length=240, null=True)),
                ('flat_type', models.CharField(blank=True, max_length=240, null=True)),
                ('cart_id', models.CharField(max_length=240)),
                ('provider_name', models.CharField(blank=True, max_length=240, null=True)),
                ('provider_type', models.CharField(blank=True, max_length=240, null=True)),
                ('days', models.IntegerField(blank=True, default=0, null=True)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'verbose_name': '\u0414\u043e\u0441\u0442\u0430\u0432\u043a\u0430',
                'verbose_name_plural': '\u0414\u043e\u0441\u0442\u0430\u0432\u043a\u0430',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('cart_id', models.CharField(max_length=240, unique=True)),
                ('is_paid', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '\u041e\u0431\u044c\u0435\u043a\u0442 \u0437\u0430\u043a\u0430\u0437\u0430',
                'verbose_name_plural': '\u0417\u0430\u043a\u0430\u0437\u044b',
            },
        ),
    ]
