# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='city_type',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='delivery',
            name='country',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='delivery',
            name='flat',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='delivery',
            name='flat_type',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='delivery',
            name='house',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='delivery',
            name='house_type',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='delivery',
            name='postal_code',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='delivery',
            name='region',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='delivery',
            name='region_type',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='delivery',
            name='street',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='delivery',
            name='street_type',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='city',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
