# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='weight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
