# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20170306_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='area',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='area_type',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='settlement',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='settlement_type',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
