# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20170306_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='block',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='block_type',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
