# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20170307_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='provider_days',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='provider_name',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='provider_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='provider_type',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
