# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20170307_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='provider_days',
            new_name='days',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='provider_price',
        ),
    ]
