# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20170307_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
