# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 21:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20170307_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
