# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, unique=True),
        ),
    ]
